language: bash
services: docker

install:
  - git clone --depth 1 https://github.com/docker-library/official-images.git ~/official-images

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      image='traefik-official'
      docker build -t "$image" ./alpine/
      ~/official-images/test/run.sh "$image"
    )
